
        var width = 800;
        var height = 800;
        var svg = d3.select("#svgcontainer")
           .append("svg")
           .attr("width", width)
           .attr("height", height);
        svg.append("line")
           .attr("x1", 100)
           .attr("y1", 300)
           .attr("x2", 700)
           .attr("y2", 300)
           .style("stroke", "rgb(255,0,0)")
           .style("stroke-width", 2);
           svg.append("line")
           .attr("x1", 700)
           .attr("y1", 300)
           .attr("x2", 200)
           .attr("y2", 700)
           .style("stroke", "rgb(255,0,0)")
           .style("stroke-width", 2);
           svg.append("line")
           .attr("x1", 200)
           .attr("y1", 700)
           .attr("x2", 400)
           .attr("y2", 100)
           .style("stroke", "rgb(255,0,0)")
           .style("stroke-width", 2);
           svg.append("line")
           .attr("x1", 400)
           .attr("y1", 100)
           .attr("x2", 600)
           .attr("y2", 700)
           .style("stroke", "rgb(255,0,0)")
           .style("stroke-width", 2);
           svg.append("line")
           .attr("x1", 600)
           .attr("y1", 700)
           .attr("x2", 100)
           .attr("y2", 300)
           .style("stroke", "rgb(255,0,0)")
           .style("stroke-width", 2);
        
            // svg.append("circle")
            // .attr("cx", 100)
            // .attr("cy", 300)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 700)
            // .attr("cy", 300)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 200)
            // .attr("cy", 700)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 400)
            // .attr("cy", 100)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 600)
            // .attr("cy", 700)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 400)
            // .attr("cy", 540)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 515)
            // .attr("cy", 455)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 285)
            // .attr("cy", 455)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 330)
            // .attr("cy", 300)
            // .attr("r", 30)
            // .attr("fill", "red")
            // svg.append("circle")
            // .attr("cx", 470)
            // .attr("cy", 300)
            // .attr("r", 30)
            // .attr("fill", "red")
     